---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-video-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: amazon-prime-video
  template:
    metadata:
      labels:
        app: amazon-prime-video
    spec:
      containers:
      - name: amazon-prime-video-container
        image: arulmurugan786/amazon-prime-video
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: amazon-prime-video-service
spec:
  
  selector:
    app: amazon-prime-video
  ports:
  - protocal: TCP
    port: 80
    targetPort: 3000
    nodePort: 31502
  type: NodePort



