apiVersion: v1
kind: Service
metadata:
  name: amazon-prime-video-service
spec:
  type: NodePort
  selector:
    app: amazon-prime-video
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31502

